#!/bin/bash
# author: github.com/felipepegoraro
# about.: compile all test.c (test files)

total_dir=0
acc_compile=0

get_total_of_dirs(){
  total_dir=$(find . -maxdepth 1 -type d \
    -not -regex "\.\($\|\/\.git\|\/anothers\)" \
    -regextype posix-egrep \
    | wc -l
  )
}

clean(){
  find . -name '*.out' -print0 | xargs -0 rm -f
}

compile_and_echo()
{
  local compiler=$1
  ((acc_compile++))

  local folder_name
  folder_name=$(basename "$PWD")

  printf "[%d/%d]: compilando %s\n" $acc_compile $total_dir $folder_name
  "$compiler" -Wall -Wextra -O2 -o "$folder_name".out ./*."$2"
}

main()
{
  if [ "$1" == "-c" ]; 
  then
    clean "$@"
    echo "deleted: *.out"
  else
    get_total_of_dirs

    for dir in */; do
      cd "$dir" || exit

      if [ -f test.c ]; then
        compile_and_echo gcc c
      # elif [ -f test.cpp ]; then
        # compile_and_echo g++ cpp
      fi

      cd ..
    done
  fi
}

main "$@"
