#!/bin/bash
# autor: github.com/felipepegoraro
# compile all test.c (test files)

total_dir=0
acc_compile=0

## pre-requisitos ============================================
prepare_dir_p1() {
  cp ./lista_sequencial/lista.* ./pilha_com_lista_sequencial/.
}

prepare_dir_p2() { 
  rm ./pilha_com_lista_sequencial/lista.*
}
## pre-requisitos ============================================


## funções auxiliares ========================================
get_total_of_dirs(){
  total_dir=$(find . -maxdepth 1 -type d \
    -not -regex "\.\($\|\/\.git\)" \
    -regextype posix-egrep \
    | wc -l
  )
}

clean(){
  find . -name '*.out' -print0 | xargs -0 rm -f
}

compile_and_echo()
{
  local compiler=$1
  ((acc_compile++))

  local folder_name
  folder_name=$(basename "$PWD")

  echo "[$acc_compile/$total_dir]: compilando: $folder_name"
  "$compiler" -Wall -Wextra -O2 -o "$folder_name".out ./*."$2"
}
## funções auxiliares ========================================


## função principal para compilar arquivos de teste =========
main()
{
  if [ "$1" == "-c" ]; 
  then
    clean "$@"
    echo "deleted: *.out"
  else
    get_total_of_dirs

    for dir in */; do
      cd "$dir" || exit

      if [ -f test.c ]; then
        compile_and_echo gcc c
      elif [ -f test.cpp ]; then
        compile_and_echo g++ cpp
      fi

      cd ..
    done
  fi
}
## função principal para compilar arquivos de teste =========

prepare_dir_p1
main "$@"
prepare_dir_p2
